name: RunDocGenerator

on:
  release:
    types:
    - created
    
jobs:
  generate_job:
    runs-on:  'windows-latest'
    
    steps:
      - name: Invoke documentation generator
        run: curl -X POST -H 'Authorization: token ${{DOC_TOKEN}}' -d '{"event_type": "generate"} https://api.github.com/repos/mianalysis/mianalysis.github.io/dispatches
