name: RunDocGenerator

on:
  release:
    types:
    - created
    
jobs:
  generate_job:
    runs-on:  'ubuntu-latest'
    
    steps:
      - name: Invoke documentation generator
        run: curl --request POST "https://api.github.com/repos/mianalysis/mianalysis.github.io/dispatches" --header 'Accept=application/vnd.github.v3+json' --header 'Authorization=token ${{DOCS_TOKEN}}' --data '{"event_type":"generate"}'
